name: Run Tests
on:
  push:
    branches: [ develop, main ]
  pull_requests:
     branches: [ develop ]
jobs:
  create-virtualenv:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      users: actions/checkout@v2
