name: Build and Publish
on:
  workflow_run:
    workflows: ["Run Tests"]
    branches: [ main ]
    types:
    - completed
    paths:
      - "producer/**"
jobs:
  build-and-push-docker-image:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Build Docker image and push to repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
