name: Run Tests
on:
  push:
    branches: [ develop, main ]
  pull_request:
     branches: [ develop ]
jobs:
  create-virtualenv:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
