name: Trigger Jenkins
on:
  workflow_run:
    workflows: ["Build and Publish"]
    types:
    - completed
jobs:
  Trigger:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Trigger Jenkins job
    steps:
    - name: echo commit sha
      run: full_commit_SHA="${{ github.event.workflow_run.head_sha }}" && short_commit_SHA=$(echo "${full_commit_SHA:0:7}") && echo "SHA=$short_commit_SHA"
